version: '3.8'
services:
  database:
    image: postgres:12.4
    ports:
      - 5432:5432
    env_file:
      - database.env # configure postgres
    volumes:
      - ./data/:/var/lib/postgresql/data/ # persist data even if container shuts down

